import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;

public class SHA1
{
    public static String sha(String i)
    {
        String hash="";
        try{
        MessageDigest m=MessageDigest.getInstance("sha-1");
        byte[] message=m.digest(i.getBytes());
        BigInteger n=new BigInteger(1,message);
        hash=n.toString(16);
        while(hash.length()<32)
         {  
             hash="0"+hash;
         }
    
        }
        catch(NoSuchAlgorithmException e)
        {
            e.printStackTrace();
        }
        return hash;
    }
    public static void main(String[] arg)
    {
        Scanner obj=new Scanner(System.in);
        String a=obj.nextLine();
        System.out.print("Hascode Generated by Sha-1 algorithm"+sha(a));
        
    }
}